language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: V5PxrrgKDH63Va1vCKJBl5JVGO8ehF2kx6UxsXk7BLNiyBDfy2CuIqr/zaiuQXEFiUjSr4d9KR8CVcwBKzoYxfizOoS6HVaz/Kn7PiyK4M60ogTsRrxZVrMDPvDIATBYBdHAZQnNUVH933k7SRNGoe2stjefJzYOOZ5wzE2OVczipA7FfGO2A//A65kcd/wuxBRNb27Nkoji+K3jGkxcRQKpd1mGW37kBRCKar61ijY82XigIaIDhYBOfIWTmVp/icLdvfEGfmmDxpai+HmYxYaGVqmoMfCTib4fI/RIaaNbmrqdRmnn+XgfzFlU97WLM7jM31L1QRZniFqtmUSlKSZXJAHm1GM0Yf1haGvO6ugzJURB2UeTKJUErZa7e2k7GSyHMsah7id8yTxSW7NY/98GYAi14xSHhz0WtWkMBCS/ViT+6qq2+6YYZl938WBP9umBgqEv66j/D8l03NperVcPWLzl5XCr1A/ZmBV9PglLFlyE7U4jutFdC87pxpqlkeqqjzvvhbY4QWdeTD5ZQZZt3RZT6fNTicZPDadqaYGg/U4Hk0jmQkk+jMO0O1IWbbk8n5hmi/TWBJ6pQXToBjmXC9MbXqQZ7faBo2NI/oMJPptrjQRRD+aYzIwM+RI7sXrsSaVFZHGgNQOg6DGazmZQOK8IsCpfEb+gNrThC7U=
  app: question-bank-sakivks
  on:
    all_branches: true
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    secure: "PbARQskrqW5OkouGlTx2qreJyyJlecd5cLUXI7XHjSL10xA21yknyHoIDH7/d/bCuLjJ9AlnRLzxXQuE5AtSpI0h34XrgPP/3BfPr70b89zJPpO4elQk3jzSfWPsWAi+uBPEIQcqVqm9iShe4p+2FZ3rs0vl9ecjBLnU2qbjSQvoYqI5kEsGY9LaZZ7DRhswlncbdaHyXBv2hjt408cb33b1C8/riw9MzyZiBcG2KcUZPclyaw8YxFOdQVp87ipqFRxZGJDFl4bksAj6FPzxo0XZrmgz3cD+s8M3q9ZkD2JxpxnlvpCgY6guLhhsXxmiecQQYFfmR01Y1s50ExJOjiV8r5qp9tyddwxCxxSOEfhDTfj1VP3yx390mwVWG1D9OLHVECKjZ3YN7cYLs7WmxS/aZ2mb0yv2Cb/VKg74VX6me4wGfbGF01DyQb022WDZeWM8LDdrgvmHqoxSDe9lu/nBM9jMQY5SCAv243CgzxTBKk5RHLY3QzyMPMG9rQWPhSRVN1kx2IAiGDzf4rkTF6TrbP+psul7iYMHmoxAsvcpfrDq7g7F4pvs321yEaD8N90jwvL4kzBt7CgkmLqSIbvkFzv65TE8LDm1G2OE87PhFQMB8hNH6+8VLkr2fJWMIkFj+3eOaWBaRcyPAwjsWYt2G6JaWgOBFlKwmlOoY2g="