language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
# deploy:
#   provider: heroku
#   api_key:
#     secure: V5PxrrgKDH63Va1vCKJBl5JVGO8ehF2kx6UxsXk7BLNiyBDfy2CuIqr/zaiuQXEFiUjSr4d9KR8CVcwBKzoYxfizOoS6HVaz/Kn7PiyK4M60ogTsRrxZVrMDPvDIATBYBdHAZQnNUVH933k7SRNGoe2stjefJzYOOZ5wzE2OVczipA7FfGO2A//A65kcd/wuxBRNb27Nkoji+K3jGkxcRQKpd1mGW37kBRCKar61ijY82XigIaIDhYBOfIWTmVp/icLdvfEGfmmDxpai+HmYxYaGVqmoMfCTib4fI/RIaaNbmrqdRmnn+XgfzFlU97WLM7jM31L1QRZniFqtmUSlKSZXJAHm1GM0Yf1haGvO6ugzJURB2UeTKJUErZa7e2k7GSyHMsah7id8yTxSW7NY/98GYAi14xSHhz0WtWkMBCS/ViT+6qq2+6YYZl938WBP9umBgqEv66j/D8l03NperVcPWLzl5XCr1A/ZmBV9PglLFlyE7U4jutFdC87pxpqlkeqqjzvvhbY4QWdeTD5ZQZZt3RZT6fNTicZPDadqaYGg/U4Hk0jmQkk+jMO0O1IWbbk8n5hmi/TWBJ6pQXToBjmXC9MbXqQZ7faBo2NI/oMJPptrjQRRD+aYzIwM+RI7sXrsSaVFZHGgNQOg6DGazmZQOK8IsCpfEb+gNrThC7U=
#   app: question-bank-sakivks